version: "2.4"
services:
  mysql_cuf:
    image: mysql:5.7
    networks:
      - cuf
    environment:
      MYSQL_USER: info
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nuit
    ports:
      - "3306:3306"
  
  cuf_game:
    image: yermangderrff/cuf-game:latest
    networks:
      - cuf 
    environment: 
      DB_HOST: mysql_cuf
    ports:
      - "8080:8080"

  cuf_secret:
    image: yermangderrff/cuf-secret:latest
    networks:
      - cuf     
    environment: 
      DB_HOST: mysql_cuf
    ports:
      - "8081:8080"

networks:
  cuf:
